FROM golang:1.18-alpine as builder

RUN mkdir /app

COPY . /app

WORKDIR /app

RUN CGO_ENABLED=0 go build -o eventConsumerApp ./cmd/api

RUN chmod +x /app/eventConsumerApp

FROM alpine:latest

RUN mkdir /app

COPY --from=builder /app/eventConsumerApp /app

CMD ["/app/eventConsumerApp"]